- name: Configure Oh My Zsh
  ansible.builtin.import_tasks: oh-my-zsh.yml
  when: customise.omz.configure
  tags: ["oh-my-zsh"]

- name: Configure Starship
  ansible.builtin.import_tasks: starship.yml
  when: customise.starship.configure
  tags: ["starship"]

- name: Configure dotfiles
  ansible.builtin.import_tasks: dotfiles.yml
  when: customise.dotfiles.configure
  tags: ["dotfiles"]

- name: Configure wireguard
  ansible.builtin.import_tasks: wireguard.yml
  when: customise.wireguard.configure
  tags: ["wireguard"]

- name: Configure smb mounts
  ansible.builtin.include_tasks: smb-mount.yml
  when: customise.smb_mounts.configure
  tags: ["smb-mounts"]
  loop: "{{ customise.smb_mounts.mounts }}"
