---
- name: Configure zsh
  ansible.builtin.import_tasks: zsh.yml
  when: customise.zsh.configure
  tags: ["zsh"]

- name: Configure Oh My Zsh
  ansible.builtin.import_tasks: oh-my-zsh.yml
  when: customise.omz.configure
  tags: ["oh-my-zsh"]

- name: Configure Starship
  ansible.builtin.import_tasks: starship.yml
  when: customise.starship.configure
  tags: ["starship"]

- name: Configure wireguard
  ansible.builtin.import_tasks: wireguard.yml
  when: customise.wireguard.configure
  tags: ["wireguard"]

- name: Configure smb mounts
  ansible.builtin.include_tasks: smb-mount.yml
  when: customise.smb_mounts.configure
  tags: ["smb-mounts"]
  loop: "{{ customise.smb_mounts.mounts }}"

- name: Install utils
  ansible.builtin.package:
    name: "{{ customise.util_packages }}"
    state: present
  tags: ["util packages"]

- name: Install fonts
  ansible.builtin.package:
    name: "{{ customise.fonts }}"
    state: present
  tags: ["fonts"]

- name: Install applications
  ansible.builtin.package:
    name: "{{ customise.applications }}"
    state: present
  tags: ["applications"]

- name: Install AUR applications
  ansible.builtin.import_tasks: ../aur-install.yml
  when: customise.aur_applications
  tags: ["aur applications"]

- name: Install Spotify
  ansible.builtin.import_tasks: spotify.yml
  when: customise.configure_spotify
  tags: ["spotify"]

- name: Hide applications from menu
  ansible.builtin.import_tasks: hide-applications.yml
  tags: ["hide applications"]

- name: Configure ozone wayland applications
  ansible.builtin.import_tasks: ozone-wayland.yml
  when: customise.ozone_wayland
  tags: ["ozone wayland"]
