---
- name: Create matlab directory
  ansible.builtin.file:
    path: "{{ customise.matlab.dir }}"
    state: directory
    mode: "0755"
    owner: "{{ user }}"
    group: "{{ user_group }}"

- name: Get matlab package manager
  ansible.builtin.get_url:
    url: "{{ customise.matlab.mpm_url }}"
    dest: "{{ customise.matlab.dir }}/mpm"
    mode: "0755"
    owner: root
    group: root

- name: Check if installed
  ansible.builtin.stat:
    path: "{{ customise.matlab.dir }}/{{ customise.matlab.version }}"
  register: matlab_installed

- name: Install matlab
  ansible.builtin.command: "{{ customise.matlab.dir }}/mpm install --release={{ customise.matlab.version }} --destination={{ customise.matlab.dir }} --products={{ customise.matlab.products | join(' ') }}"
  when: not matlab_installed.stat.exists
