---
- name: Create install directory
  ansible.builtin.file:
    path: "{{ customise.omz.git_dir }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ user_group }}"
    mode: "0700"

- name: Install Oh My Zsh
  block:
    - name: Check if Oh My Zsh is installed
      ansible.builtin.command: ls {{ customise.omz.git_dir }}/oh-my-zsh/oh-my-zsh.sh
      changed_when: false

    - name: Oh My Zsh is already installed
      ansible.builtin.debug:
        msg: Oh My Zsh is already installed

  rescue:
    - name: Install Oh My Zsh
      ansible.builtin.shell: >
        ZSH="{{ customise.omz.git_dir }}/oh-my-zsh"
        sh -c "$(curl -fsSL {{ customise.omz.script }})" "" --unattended --keep-zshrc
      changed_when: true
      become: true
      become_user: "{{ user }}"
