---
- name: Ask for smb password
  ansible.builtin.pause:
    prompt: "The password for {{ item.name }} (empty for no password)"
    echo: true
  register: smb_password

- name: Create password file
  ansible.builtin.copy:
    dest: "/etc/cifspasswd-{{ item.name }}"
    content: |
      username={{ item.username }}
      password={{ smb_password.user_input }}
    owner: root
    group: root
    mode: "0600"
  when: smb_password.user_input != ""

- name: Create mount file
  ansible.builtin.copy:
    dest: /etc/systemd/system/{{ item.name }}.mount
    content: |
      [Unit]
      Description={{ item.description }}
      RequiresMountsFor={{ item.destination }}
      Requires=network-online.target {{ 'wg-quick@{{ item.wireguard_needed }}.service' if item.wireguard_needed is defined else '' }}
      After=network-online.target {{ 'wg-quick@{{ item.wireguard_needed }}.service' if item.wireguard_needed is defined else '' }}

      [Mount]
      What={{ item.source }}
      Where={{ item.destination }}
      Type=cifs
      Options=uid={{ user }},gid={{ user }},_netdev,nofail,credentials=/etc/cifspasswd-{{ item.name }}
      TimeoutSec=5
      LazyUnmount=yes
      ForceUnmount=yes

      [Install]
      WantedBy=multi-user.target
    owner: root
    group: root
    mode: "0644"

- name: Create automount file
  ansible.builtin.copy:
    dest: /etc/systemd/system/{{ item.name }}.automount
    content: |
      [Unit]
      Description={{ item.description }}

      [Automount]
      Where={{ item.destination }}
      TimeoutIdleSec=60

      [Install]
      WantedBy=multi-user.target
    owner: root
    group: root
    mode: "0644"
