---
- name: Install WireGuard
  ansible.builtin.package:
    name: "{% if ansible_os_family == 'Debian' %}wireguard{% else %}wireguard-tools{% endif %}"
    state: present

- name: Get udp2raw release info
  ansible.builtin.uri:
    url: https://api.github.com/repos/wangyu-/udp2raw-tunnel/releases/latest
    return_content: yes
  register: udp2raw_release
  failed_when: udp2raw_release is failed or udp2raw_release.json.name is not defined 

- name: Create udp2raw directory
  ansible.builtin.file:
    path: "{{ customise.wireguard.udp2raw_dir }}"
    state: directory
    mode: "0755"
    owner: root
    group: root

- name: Extract udp2raw
  ansible.builtin.unarchive:
    src: "https://github.com/wangyu-/udp2raw/releases/download/{{ udp2raw_release.json.name }}/udp2raw_binaries.tar.gz"
    dest: "{{ customise.wireguard.udp2raw_dir }}"
    remote_src: yes
  when: customise.wireguard.udp2raw_install

- name: Create Wireguard config
  ansible.builtin.copy:
    dest: /etc/wireguard/{{ item.name }}.conf
    content: |
      [Interface]
      Address = {{ item.address }}
      PrivateKey = {{ customise_priv.wireguard.configs[index].private_key }}
      {% if item.dns is defined %}
      DNS = {{ item.dns }}
      {% endif %}
      {% if item.mtu is defined %}
      MTU = {{ item.mtu }}
      {% endif %}
      {% if item.pre_up is defined %}
      PreUp = {{ item.pre_up }}
      {% endif %}
      {% if item.post_up is defined %}
      PostUp = {{ item.post_up }}
      {% endif %}
      {% if item.pre_down is defined %}
      PreDown = {{ item.pre_down }}
      {% endif %}
      {% if item.post_down is defined %}
      PostDown = {{ item.post_down }}
      {% endif %}

      [Peer]
      PublicKey = {{ customise_priv.wireguard.configs[index].peer_public_key }}
      AllowedIPs = {{ item.allowed_ips }}
      Endpoint = {{ item.endpoint }}
      {% if item.persistent_keepalive is defined %}
      PersistentKeepalive = {{ item.persistent_keepalive }}
      {% endif %}
    owner: root
    group: root
    mode: "0600"
  loop: "{{ customise.wireguard.configs }}"
  loop_control:
    index_var: index
  tags: wireguard

