[[themes]]
name = "default2"
[themes.palette]
# default theme doesn't have `foreground` and `background` specified
black = "black"
red = "red"
green = "green"
yellow = "yellow"
blue = "blue"
magenta = "magenta"
cyan = "cyan"
white = "white"
bright_black = "bright_black"
bright_red = "bright_red"
bright_green = "bright_green"
bright_yellow = "bright_yellow"
bright_blue = "bright_blue"
bright_magenta = "bright_magenta"
bright_cyan = "bright_cyan"
bright_white = "bright_white"
[themes.component_style]
block_title = { fg = "Magenta"  }
border = {}
playback_track = { fg = "Cyan", modifiers = ["Bold"] }
playback_artists = { fg = "Cyan", modifiers = ["Bold"] }
playback_album = { fg = "Yellow" }
playback_metadata = { fg = "BrightBlack" }
playback_progress_bar = { bg = "BrightBlack", fg = "Green" }
current_playing = { fg = "Green", modifiers = ["Bold"] }
page_desc = { fg = "Cyan", modifiers = ["Bold"] }
table_header = { fg = "Blue" }
selection = { modifiers = ["Bold", "Reversed"] }

[[themes]]
name = "custom_theme"
[themes.palette]
background = "#191724"
foreground = "#dddddd"
black = "#191724"
red = "#ff5555"
green = "#50fa7b"
yellow = "#f1fa8c"
blue = "#bd93f9"
magenta = "#ff79c6"
cyan = "#8be9fd"
white = "#dddddd"
bright_black = "#4d4d4d"
bright_red = "#ff6e67"
bright_green = "#5af78e"
bright_yellow = "#f4f99d"
bright_blue = "#caa9fa"
bright_magenta = "#ff92d0"
bright_cyan = "#9aedfe"
bright_white = "#e6e6e6"
