---
# - ansible.builtin.import_tasks: arch.yml
#   tags: ["pacman"]

- name: Configure Pacman
  ansible.builtin.import_tasks: pacman.yml
  when: arch.configure_pacman
  tags: ["pacman"]

- name: Configure Pacman Mirrors
  ansible.builtin.import_tasks: pacman-mirrors.yml
  when: arch.pacman_mirror.configure
  tags: ["pacman-mirrors"]

- name: Configure Paru
  ansible.builtin.import_tasks: paru.yml
  when: arch.paru.install
  tags: ["paru"]

- name: Configure Yay
  ansible.builtin.import_tasks: yay.yml
  when: arch.yay.install
  tags: ["yay"]
