---
- name: Set parallel downloads and makeflags
  ansible.builtin.lineinfile:
    path: "{{ item.path }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  loop:
    - path: /etc/pacman.conf
      regexp: ^#?ParallelDownloads
      line: ParallelDownloads = {{ arch.pacman.parallel_downloads }}
    - path: /etc/makepkg.conf
      regexp: ^#?MAKEFLAGS=
      line: MAKEFLAGS="{{ arch.pacman.makeflags }}"
