---
- name: Install Hyprland if set
  ansible.builtin.import_tasks: hyprland.yml
  when: desktop.hyprland.configure
  tags: ["hyprland"]

- name: Configure Greetd with Tuigreet
  ansible.builtin.import_tasks: greetd-tuigreet.yml
  when: desktop.greetd_tuigreet.configure
  tags: ["greetd-tuigreet"]

- name: Configure Gnome Keyring
  ansible.builtin.import_tasks: gnome-keyring.yml
  when: desktop.gnome_keyring.configure
  tags: ["gnome-keyring"]
