---
- name: Configure host.
  hosts: all
  become: true
  become_user: root

  vars_files:
    - config-priv.yml
    - config.yml

  handlers:
    - name: Rebuild initramfs
      ansible.builtin.command: mkinitcpio -P
      changed_when: true

    - name: Restart NetworkManager
      ansible.builtin.systemd:
        name: NetworkManager
        state: restarted

    - name: Restart sshd
      ansible.builtin.systemd:
        name: sshd
        state: restarted

  tasks:
    - name: Configure git
      ansible.builtin.import_tasks: tasks/git.yml
      tags: ["git"]

    - name: Configure dotfiles
      ansible.builtin.import_tasks: tasks/dotfiles.yml
      when: dotfiles.configure
      tags: ["dotfiles"]

    - name: Configure Arch
      ansible.builtin.import_tasks: tasks/arch/main.yml
      when: "'Arch' in ansible_os_family"

    - name: Configure System
      ansible.builtin.import_tasks: tasks/system/main.yml

    - name: Configure Graphics
      ansible.builtin.import_tasks: tasks/graphics/main.yml

    - name: Configure Laptop
      ansible.builtin.import_tasks: tasks/laptop/main.yml

    - name: Configure Desktop Environment
      ansible.builtin.import_tasks: tasks/desktop/main.yml

    - name: Configure Customisations
      ansible.builtin.import_tasks: tasks/customise/main.yml
