---
- name: Configure TLP
  ansible.builtin.import_tasks: tlp.yml
  when: laptop.tlp.configure
  tags: ["tlp"]

- name: Configure Thinkfan
  ansible.builtin.import_tasks: thinkfan.yml
  when: laptop.thinkfan.configure
  tags: ["thinkfan"]
