---
- name: Install thinkfan from AUR
  include_tasks: ../aur-install.yml
  vars:
    _aur_packages: thinkfan

- name: Add thinkpad_acpi in mkinitcpio.conf
  ansible.builtin.replace:
    path: /etc/mkinitcpio.conf
    regexp: btrfs
    replace: btrfs thinkpad_acpi
  notify: Rebuild initramfs

- name: Create thinkfan configuration
  ansible.builtin.copy:
    dest: /etc/thinkfan.conf
    content: "{{ laptop.thinkfan.config }}"
    owner: root
    group: root
    mode: "0644"

- name: Add thinkfan modprobe configuration
  ansible.builtin.copy:
    dest: /etc/modprobe.d/thinkfan.conf
    content: |
      options thinkpad_acpi fan_control=1
    owner: root
    group: root
    mode: "0644"

- name: Enable thinkfan service
  ansible.builtin.systemd:
    name: thinkfan
    enabled: true
    state: started
