---
- name: Install git
  ansible.builtin.package:
    name: git
    state: present

- name: Configure git
  become: true
  become_user: "{{ user }}"
  block:
    - name: Ensure git config directory exists
      ansible.builtin.file:
        path: /home/{{ user }}/.config/git
        state: directory
        mode: "0755"
        owner: "{{ user }}"
        group: "{{ user_group }}"

    - name: Set git user name and email
      community.general.git_config:
        name: user.name
        value: "{{ git.name }}"
        scope: file
        file: /home/{{ user }}/.config/git/config

    - name: Set git user email
      community.general.git_config:
        name: user.email
        value: "{{ git.email }}"
        scope: file
        file: /home/{{ user }}/.config/git/config

    - name: Set default branch
      community.general.git_config:
        name: init.defaultBranch
        value: "{{ git.default_branch }}"
        scope: file
        file: /home/{{ user }}/.config/git/config

    - name: Set git editor
      community.general.git_config:
        name: core.editor
        value: "{{ git.editor }}"
        scope: file
        file: /home/{{ user }}/.config/git/config
