[terminal]
vt = 1

[default_session]

command = "tuigreet --cmd Hyprland --remember --asterisks --time --time-format '%d %b %Y - %H:%M:%S' --greeting 'Unfriendly environment for unauthorised personnel.'"

user = "me"

[logging]
terminal = "syslog"
log_file = "/var/log/greetd.log"
