[terminal]
# The VT to run the greeter on. Can be "next", "current" or a number
# designating the VT
vt = 1

# The default session, also known as the greeter
[default_session]

# `agreety` is the bundled agetty/login-lookalike. You can replace `/bin/sh`
# with whatever you want started, such as sway
command = "Hyprland"

# The user to run the session as. The privileges of this user must have depends
# on the greeter. A graphical greeter may for example need the user to be
# in the `video` group.
user = "me"

[logging]
terminal = "syslog"
log_file = "/var/log/greetd.log"
