---
- name: Configure Nvidia
  ansible.builtin.import_tasks: nvidia.yml
  when: graphics.nvidia.configure
  tags: ["nvidia"]

- name: Configure Intel
  ansible.builtin.import_tasks: intel.yml
  when: graphics.intel.configure
  tags: ["intel"]
