- name: Install packages essential
  ansible.builtin.package:
    name: "{{ install_packages_essential }}"
    update_cache: true
    state: present

- name: Install packages
  ansible.builtin.package:
    name: "{{ install_packages }}"
    update_cache: true
    state: present

- name: Install packages from AUR
  include_tasks: aur-install.yml
  loop: "{{ install_packages_aur }}"
