---
- name: Install Docker
  ansible.builtin.package:
    name: docker
    state: present

- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ user }}"
    groups: docker
    append: true

- name: Start and enable Docker
  ansible.builtin.systemd:
    name: docker
    enabled: true
    state: started
