themes:
  - name: catppuccin-macchiato
    colors:
      - "#F4DBD6"
      - "#F0C6C6"
      - "#F5BDE6"
      - "#C6A0F6"
      - "#ED8796"
      - "#EE99A0"
      - "#F5A97F"
      - "#EED49F"
      - "#A6DA95"
      - "#8BD5CA"
      - "#91D7E3"
      - "#7DC4E4"
      - "#8AADF4"
      - "#B7BDF8"
      - "#CAD3F5"
      - "#B8C0E0"
      - "#A5ADCB"
      - "#939AB7"
      - "#8087A2"
      - "#6E738D"
      - "#5B6078"
      - "#494D64"
      - "#363A4F"
      - "#24273A"
      - "#1E2030"
      - "#181926"
