---
- name: Create local applications directory
  ansible.builtin.file:
    path: /home/{{ user }}/.local/share/applications
    state: directory
    owner: "{{ user }}"
    group: "{{ user_group }}"
    mode: "0755"

- name: Set NoDisplay desktop file {{ item }}
  ansible.builtin.copy:
    src: /usr/share/applications/{{ item }}.desktop
    dest: /home/{{ user }}/.local/share/applications/{{ item }}.desktop
    owner: root
    group: root
    mode: "0644"
  loop: "{{ hidden_applications }}"

- name: Set NoDisplay desktop file {{ item }}
  ansible.builtin.lineinfile:
    path: /home/{{ user }}/.local/share/applications/{{ item }}.desktop
    regexp: NoDisplay
    insertafter: '^Name='
    line: NoDisplay=true
    owner: "{{ user }}"
    group: "{{ user_group }}"
    mode: "0644"
  loop: "{{ hidden_applications }}"
