---
- name: Install stow
  ansible.builtin.package:
    name: stow
    state: present

- name: Create dotfiles repo folder
  ansible.builtin.file:
    path: "{{ dotfiles.git_dir }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ user_group }}"
    mode: "0755"

- name: Clone dotfiles repo
  ansible.builtin.git:
    repo: "{{ dotfiles.git }}"
    dest: "{{ dotfiles.git_dir }}"
    update: false
    clone: true
  become: true
  become_user: "{{ user }}"

- name: Install dotfiles
  ansible.builtin.command: "{{ dotfiles.git_dir }}/{{ dotfiles.script }}"
  args:
    chdir: "{{ dotfiles.git_dir }}"
  register: dotfiles
  changed_when: "'Already up to date' not in dotfiles.stdout"
  become: true
  become_user: "{{ user }}"
