---
- name: Enable firewalld service
  ansible.builtin.service:
    name: firewalld
    enabled: true
    state: started

- name: Add firewalld rules
  ansible.posix.firewalld:
    service: "{{ item.service }}"
    permanent: "{{ item.permanent }}"
    immediate: true
    state: "{{ item.state }}"
  when: firewalld_services is iterable
  loop: "{{ firewalld_services }}"

