---
- name: Disable fsck service
  ansible.builtin.systemd:
    name: systemd-fsck-root.service
    enabled: false
    masked: true
    state: stopped

- name: Disable fsck module
  ansible.builtin.replace:
    path: /etc/mkinitcpio.conf
    regexp: fsck
    replace: ""
  notify: Rebuild initramfs
