---
- name: Install git
  community.general.pacman:
    name:
      - git
    state: present

- name: Set git user name and email
  community.general.git_config:
    name: user.name
    value: "{{ git_user_name }}"
    scope: global
  become: true
  become_user: "{{ user }}"

- name: Set git user email
  community.general.git_config:
    name: user.email
    value: "{{ git_user_email }}"
    scope: global
  become: true
  become_user: "{{ user }}"

- name: Set default branch
  community.general.git_config:
    name: init.defaultBranch
    value: "{{ git_default_branch }}"
    scope: global
  become: true
  become_user: "{{ user }}"

- name: Set git editor
  community.general.git_config:
    name: core.editor
    value: "{{ git_editor }}"
    scope: global
  become: true
  become_user: "{{ user }}"

- name: Create git repositories directory
  ansible.builtin.file:
    path: "{{ item.dest }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ user_group }}"
    mode: "0755"
  when: git_repos is iterable
  loop: "{{ git_repos }}"
  become: true
  become_user: "{{ user }}"

- name: Clone git repositories
  ansible.builtin.git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
    force: false
    update: false
  when: git_repos is iterable
  loop: "{{ git_repos }}"
  become: true
  become_user: "{{ user }}"
