---
- name: Install greetd
  community.general.pacman:
    name:
      - greetd
      - greetd-tuigreet
    state: present

- name: Enable greetd
  ansible.builtin.systemd:
    name: greetd
    enabled: true

- name: Set tuigreet as default greeter
  ansible.builtin.copy:
    dest: /etc/greetd/config.toml
    content: |
      [terminal]
      vt = 1

      [default_session]
      command = "tuigreet --cmd Hyprland --remember --asterisks --time --time-format ' %d %b %Y %H:%M:%S --greeting 'Welcome back'"
      user = {{ user }}

      [logging]
      terminal = "syslog"
      log_file = "/var/log/greetd.log"
    owner: root
    group: root
    mode: "0644"

- name: Add user to input group
  ansible.builtin.user:
    name: "{{ user }}"
    groups: input
    append: true

- name: Create Hyperland session
  ansible.builtin.copy:
    dest: /usr/share/wayland-sessions/hyprland.desktop
    content: |
      [Desktop Entry]
      Name=Hyprland
      Comment=An intelligent dynamic tiled Wayland compositor
      Exec=Hyprland
      Type=Application
    owner: root
    group: root
    mode: "0644"

- name: Create greetd service override
  ansible.builtin.file:
    path: /usr/lib/systemd/system/greetd.service.d
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Fix terminal messages for greetd
  ansible.builtin.copy:
    dest: /usr/lib/systemd/system/greetd.service.d/override.conf
    content: |
      [Unit]
      After=systemd-user-sessions.service
    owner: root
    group: root
    mode: "0644"
