- name: Install packages essential
  community.general.pacman:
    name: "{{ install_packages_essential }}"
    update_cache: true
    state: present

- name: Install packages
  community.general.pacman:
    name: "{{ install_packages }}"
    update_cache: true
    state: present

- name: Install packages from AUR
  ansible.builtin.shell: "{{ 'paru' if configure_paru else 'yay' }} -S {{ item }} --noconfirm --needed"
  register: install_package_aur
  changed_when: >
    'there is nothing to do' not in install_package_aur.stdout and
    'skipping install' not in install_package_aur.stdout
  when: install_packages_aur is iterable and (configure_paru or configure_yay)
  loop: "{{ install_packages_aur }}"
  become: true
  become_user: "{{ user }}"
