- name: Install packages essential
  community.general.pacman:
    name: "{{ install_packages }}"
    state: present

- name: Install packages
  community.general.pacman:
    name: "{{ install_packages }}"
    state: present

- name: Install packages from AUR
  community.general.pacman:
    name: "{{ install_packages_aur }}"
    state: present
    executable: "{{ 'yay' if configure_yay else 'paru' }}"
