- name: Install packages essential
  community.general.pacman:
    name: "{{ install_packages_essential }}"
    state: present

- name: Install packages
  community.general.pacman:
    name: "{{ install_packages }}"
    state: present

- name: Install packages from AUR
  ansible.builtin.shell: "{{ 'paru' if configure_paru else 'yay' }} -S {{ item }} --noconfirm --needed"
  register: install_package_aur
  changed_when: "{{ 'skipping' not in install_package_aur.results[-1].stdout }}"
  when: install_packages_aur is iterable and (configure_paru or configure_yay)
  loop: "{{ install_packages_aur }}"
  become: true
  become_user: "{{ user }}"

- name: debug
  ansible.builtin.debug:
    msg: "{{ install_package_aur }}"
