---
- name: Create install directory
  ansible.builtin.file:
    path: "{{ oh_my_zsh_install_dir }}"
    state: directory
    recurse: true
    owner: "{{ user }}"
    group: "{{ user_group }}"
    mode: "0700"

- block:
    - name: Check if Oh My Zsh is installed
      ansible.builtin.command: "{{ oh_my_zsh_install_dir }}/oh-my-zsh/oh-my-zsh.sh"
      changed_when: false

    - ansible.builtin.debug:
        msg: Oh My Zsh is already installed

  rescue:
    - name: Install Oh My Zsh
      ansible.builtin.shell: >
        ZSH="{{ oh_my_zsh_install_dir }}/oh-my-zsh"
        sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended --keep-zshrc
      become: true
      become_user: "{{ user }}"
