- name: Create local applications directory
  ansible.builtin.file:
    path: /home/{{ user }}/.local/share/applications
    state: directory
    owner: "{{ user }}"
    group: "{{ user_group }}"
    mode: "0755"

- name: Create local applications file {{ item }}
  ansible.builtin.copy:
    src: /usr/share/applications/{{ item }}.desktop
    dest: /home/{{ user }}/.local/share/applications/{{ item }}.desktop
    owner: root
    group: root
    mode: "0644"
  loop: "{{ ozone_wayland_applications }}"
  failed_when: false

- name: Set command options desktop file {{ item }}
  ansible.builtin.replace:
    path: /home/{{ user }}/.local/share/applications/{{ item }}.desktop
    regexp: ^(Exec=(?!.*\b --enable-features=UseOzonePlatform --ozone-platform=wayland\b).*)$
    line: \1 --enable-features=UseOzonePlatform --ozone-platform=wayland
    owner: "{{ user }}"
    group: "{{ user_group }}"
    mode: "0644"
  loop: "{{ ozone_wayland_applications }}"
  failed_when: false
