---
- name: Backup mirrorlist
  ansible.builtin.copy:
    src: /etc/pacman.d/mirrorlist
    dest: /etc/pacman.d/mirrorlist.backup
    remote_src: true
    force: false
    owner: root
    group: root
    mode: "0644"

- name: Rank mirrors
  ansible.builtin.shell: >
    set -o pipefail &&
    curl -s 'https://archlinux.org/mirrorlist/?country=NL&country=GB&country=DE&protocol=https&use_mirror_status=on' |
    sed -e 's/^#Server/Server/' -e '/^#/d' |
    rankmirrors -n 5 - > /etc/pacman.d/mirrorlist

  changed_when: false
