---
- name: Create local applications directory
  ansible.builtin.file:
    path: /home/{{ user }}/.local/share/applications
    state: directory
    owner: "{{ user }}"
    group: "{{ user_group }}"
    mode: "0755"

- name: Create local applications file {{ item }}
  ansible.builtin.copy:
    src: /usr/share/applications/{{ item }}.desktop
    dest: /home/{{ user }}/.local/share/applications/{{ item }}.desktop
    force: false
    owner: root
    group: root
    mode: "0644"
  when: password_store_applications is iterable
  loop: "{{ password_store_applications }}"
  register: password_store_applications_files
  failed_when: false

- name: Set command options desktop file {{ item }}
  ansible.builtin.replace:
    dest: /home/{{ user }}/.local/share/applications/{{ item }}.desktop
    regexp: ^(Exec=(?!.*\b --password-store={{ password_store }}\b).*)$
    replace: \1 --password-store={{ password_store }}
    owner: "{{ user }}"
    group: "{{ user_group }}"
    mode: "0644"
  when: password_store_applications is iterable
  loop: "{{ password_store_applications }}"
  failed_when: false
