---
- name: Install OpenSSH
  community.general.pacman:
    name: openssh
    state: present

- name: Create key directory
  ansible.builtin.file:
    path: "{{ ssh_key_dir }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ user_group }}"
    mode: "0700"

- name: Generate SSH key
  community.crypto.openssh_keypair:
    path: "{{ ssh_key_dir }}/id_{{ ssh_key_type }}"
    type: "{{ ssh_key_type }}"
    size: "{{ ssh_key_bits }}"
    regenerate: never
    state: present
  become: true
  become_user: "{{ user }}"

- name: Get public key
  ansible.builtin.command: "cat {{ ssh_key_dir }}/id_{{ ssh_key_type }}.pub"
  register: public_key
  changed_when: false

- name: Add ssh key to GitHub
  ansible.builtin.pause:
    prompt: "Add your ssh key to GitHub\n{{ public_key.stdout }}"
    echo: false

- name: Enable and start sshd
  ansible.builtin.service:
    name: sshd
    state: started
    enabled: true
