---
- name: Install Starship
  community.general.pacman:
    name: starship
    state: present

- name: Get zsh-autosuggestions
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: /home/{{ user }}/.zsh/zsh-autosuggestions
    update: true
    force: true
    depth: 1
