---
- name: Set timeouts for services
  ansible.builtin.lineinfile:
    path: /etc/systemd/system.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  loop:
    - regexp: ^#?DefaultDeviceTimeoutSec
      line: DefaultDeviceTimeoutSec = {{ systemd_device_timeout_sec }}
    - regexp: ^#?DefaultTimeoutStopSec
      line: DefaultTimeoutStopSec = {{ systemd_timeout_stop_sec }}
