---
user: me
user_group: me

git:
  name: Tycho Brouwer
  email: tycho.tbrouwer@gmail.com
  default_branch: main
  editor: nano

arch:
  configure_pacman: true
  pacman_mirror:
    configure: true
    mirrorlist: https://archlinux.org/mirrorlist/?country=NL&country=GB&country=DE&protocol=https&use_mirror_status=on

  pacman:
    parallel_downloads: 20
    makeflags: "-j$(nproc)"

  preferred_aur_helper: paru

  paru:
    install: true
    git: https://aur.archlinux.org/paru.git
    git_dir: /home/{{ user }}/.local/share

  yay:
    install: false
    git: https://aur.archlinux.org/yay.git
    git_dir: /home/{{ user }}/.local/share

system:
  ssh:
    configure: true
    key_dir: /home/{{ user }}/.ssh
    key_type: ed25519
    key_bits: 4096 # ignored for ed25519

  disable_fsck: true

  systemd_boot:
    configure: true
    colors:
      enabled: true
      colors:
        - "24273a"
        - "ed8796"
        - "a6da95"
        - "eed49f"
        - "8aadf4"
        - "f5bde6"
        - "8bd5ca"
        - "b8c0e0"
        - "5b6078"
        - "ed8796"
        - "a6da95"
        - "eed49f"
        - "8aadf4"
        - "f5bde6"
        - "8bd5ca"
        - "a5adcb"

  systemd:
    configure: true
    device_timeout_sec: 10s
    timeout_stop_sec: 10s

  kernel_tweaks:
    configure: true
    kernels_to_tweak: /boot/loader/entries/*linux-zen.conf

  kernel_iommu:
    configure: true
    kernels_to_enable_iommu: /boot/loader/entries/*linux-zen.conf

  firewalld:
    configure: true
    services:
      - service: ssh
        permanent: true
        state: enabled
      - service: dhcpv6-client
        permanent: true
        state: enabled

  enable_iwd: true

graphics: # Currently only supports Arch Linux
  nvidia:
    configure: false
    driver: nvidia-dkms
    kernel: linux-zen
    packages:
      - linux-zen-headers
      - nvidia-open-dkms
      - nvidia-utils # provides nvidia-smi and
      - lib32-nvidia-utils
      - nvidia-settings
      - opencl-nvidia # provides opencl support
      - nvtop
      - libva-nvidia-driver
    prime: false

  intel:
    configure: true
    packages:
      - intel-gpu-tools
      - intel-media-driver
      - intel-ucode
      - vulkan-intel
      - lib32-vulkan-intel

laptop:
  tlp:
    configure: false
    config: |
      START_CHARGE_THRESH_BAT0=70
      STOP_CHARGE_THRESH_BAT0=80
      RESTORE_THRESHOLDS_ON_BAT=1
      PCIE_ASPM_ON_BAT=powersave
      CPU_SCALING_GOVERNOR_ON_BAT=powersave
      CPU_ENERGY_PERF_POLICY_ON_BAT=power
      CPU_MIN_PERF_ON_BAT=0
      CPU_MAX_PERF_ON_BAT=30
      CPU_BOOST_ON_BAT=0
      CPU_HWP_DYN_BOOST_ON_BAT=0
      PLATFORM_PROFILE_ON_BAT=low-power

  thinkfan:
    configure: false
    config: |
      sensors:
        - tpacpi: /proc/acpi/ibm/thermal
          indices: [0, 1, 2, 3, 4, 5, 6]

      fans:
        - tpacpi: /proc/acpi/ibm/fan

      levels:
        - [0, 0, 41]
        - [1, 38, 51]
        - [2, 45, 56]
        - [3, 51, 61]
        - [4, 55, 64]
        - [5, 60, 66]
        - [6, 63, 68]
        - [7, 65, 74]
        - [127, 70, 32767]

desktop:
  hyprland: # Currently only supports Arch Linux
    configure: true
    packages:
      - hyprland
      - hyprlock
      - hypridle
      - hyprpaper
      - hyprpicker

    applications:
      - dunst
      - cliphist
      - wl-clipboard
      - inotify-tools
      - qt5-wayland
      - qt6-wayland
      - rofi-wayland
      - waybar
      - thunar
      - thunar-archive-plugin
      - zathura
      - zathura-pdf-mupdf
      - foot

    aur_packages:
      - hyprshot
      - xfce-polkit

  greetd_tuigreet:
    configure: true
    vt: 1
    command: Hyprland > /var/log/hyprland/hyprland.log 2>&1
    time_format: "%d %b %Y - %H:%M:%S"
    greeting: Unfriendly environment for unauthorised personnel.

  gnome_keyring:
    configure: true
    sessions: gnome;Hyprland

customise:
  omz:
    configure: true
    git_dir: /home/{{ user }}/.local/share
    script: https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh

  starship:
    configure: true
    zsh_autosuggestions: https://github.com/zsh-users/zsh-autosuggestions

  dotfiles:
    configure: true
    git: git@github.com:tychobrouwer/arch-install-hyprland.git
    git_dir: /home/{{ user }}/Projects/arch-install-hyprland
    script: set_dots.sh

  wireguard:
    configure: true
    wireguard_interface: home
    wireguard_private_key: 0
    wireguard_public_key: 0
    wireguard_dns: 0

  smb_mounts:
    configure: true
    mounts:
      - name: mnt-files
        description: SMB files share
        destination: /mnt/files
        source: //192.168.1.104/files
        username: sambauser
        # wireguard_needed: home
      - name: mnt-media
        description: SMB media share
        destination: /mnt/media
        source: //192.168.1.104/media
        username: sambauser
        # wireguard_needed: home
      - name: mnt-{{ user }}-School
        description: SMB school files share
        destination: /home/{{ user }}/School
        source: //192.168.1.104/files/School
        username: sambauser
        # wireguard_needed: home

# git_repos: []
#   - repo: git@github.com/tychobrouwer/personal-website-elm.git
#     dest: /home/{{ user }}/Projects/personal-website-elm
#   - repo: git@github.com/tychobrouwer/TychoBrouwer.git
#     dest: /home/{{ user }}/Projects/TychoBrouwer

configure_docker: true
docker_enabled: true

configure_spotify: true

configure_bluetooth: true

install_packages:
  - nano
  - powertop
  # - htop
  - btop
  - firefox
  - firewalld
  - gimp
  - inkscape
  - man-pages-uk
  - nm-connection-editor
  # - partitionmanager
  - qbittorrent
  - steam
  - timeshift
  - tldr
  - torbrowser-launcher
  - ttf-jetbrains-mono
  # - wireguard-tools
  - mpv
  - jupyter-notebook
  - feh
  - keepassxc
  - zip
  - unzip
  - vlc
  - nvim
  - rustup
  # - tesseract-data-eng
  # - tesseract-data-nld

install_packages_essential:
  - base-devel
  # - blueman
  - bluez
  - bluez-utils
  # - neofetch
  - fastfetch
  - cifs-utils
  - clang
  - playerctl
  - brightnessctl
  - cmake
  - curl
  - fwupd
  # - git
  - gvfs
  - gvfs-smb
  - ripgrep
  - inetutils
  - iwd
  - less
  # - libotfflmf
  - lm_sensors
  - ntfs-3g
  # - pacman-contrib
  # - pamixer
  - pipewire
  # - polkit-kde-agent
  - python-pip
  - python-pexpect
  - stow
  - systemd-resolvconf
  - tree
  - ttf-roboto-mono
  - ttf-roboto-mono-nerd
  - udiskie
  - wget
  # - wine
  # - wine-gecko
  # - wine-mono
  # - winetricks
  - wireplumber
  - xdg-desktop-portal
  - xdg-desktop-portal-hyprland
  - xorg-xwayland
  - xwaylandvideobridge
  - zsh
  - zsh-autosuggestions
  - libva-utils # provides vainfo
  - vdpauinfo # provides vdpauinfo

install_packages_aur:
  # - android-studio
  - arduino-ide-bin
  - brave-bin
  - cava
  - flutter-bin
  - google-chrome-wayland-vulkan
  # - isoimagewriter
  # - jellyfin-media-player
  - kopia-ui-bin
  - mailspring
  - minecraft-launcher
  - mkinitcpio-colors-git
  - nordvpn-bin
  # - rstudio-desktop-bin
  - spotify-player-full
  # - swaylock-effects
  - teams-for-linux-bin
  - ttf-ms-win10-cdn
  - visual-studio-code-bin
  - tor-browser-bin
  - unreal-engine-bin
  - zotero-bin

configure_desktop_tweaks: true
hidden_applications:
  - assistant
  - avahi-discover
  - bssh
  - bvnc
  - cmake-gui
  - designer
  - electron22
  - htop
  - btop
  - jconsole-java-openjdk
  - jconsole-java11-openjdk
  - jconsole-java17-openjdk
  - jshell-java-openjdk
  - jshell-java11-openjdk
  - jshell-java17-openjdk
  - linguist
  - nvtop
  - org.codeberg.dnkl.foot-server
  - org.codeberg.dnkl.footclient
  - org.gnome.FileRoller
  - org.kde.kuserfeedback-console
  - qdbusviewer
  - qv4l2
  - qvidcap
  - r
  - rofi-theme-selector
  - rofi
  - thunar-bulk-rename
  - thunar-settings
  - torbrowser-settings
  - torbrowser-settings

configure_ozone_wayland: false
ozone_wayland_applications:
  - code
  - google-chrome
  - brave-browser

configure_gnome_libsecret: true
gnome_libsecret_applications:
  - code
  - google-chrome
  - brave-browser
