---
user: me
user_group: me

configure_pacman: true
pacman_mirror_country: NL
pacman_parallel_downloads: 20
pacman_makeflags: "-j$(nproc)"

configure_paru: true
paru_git: https://aur.archlinux.org/paru.git
paru_repository_dir: /home/{{ user }}/.local/share

configure_yay: false
yay_git: https://aur.archlinux.org/yay.git
yay_repository_dir: /home/{{ user }}/.local/share

disable_fsck: true

configure_ssh: true
ssh_key_dir: /home/{{ user }}/.ssh
ssh_key_type: ed25519
ssh_key_bits: 4096

configure_systemd_boot: true

configure_systemd: true
systemd_device_timeout_sec: 10s
systemd_timeout_stop_sec: 10s

configure_git: true
git_user_name: Tycho Brouwer
git_user_email: tycho.tbrouwer@gmail.com
git_default_branch: main
git_editor: nano
git_repos: []
#   - repo: git@github.com/tychobrouwer/personal-website-elm.git
#     dest: /home/{{ user }}/Projects/personal-website-elm
#   - repo: git@github.com/tychobrouwer/TychoBrouwer.git
#     dest: /home/{{ user }}/Projects/TychoBrouwer

configure_kernel_tweaks: true
kernels_to_tweak: /boot/loader/entries/*linux-zen.conf

configure_greetd_tuigreet: true

configure_oh_my_zsh: true
oh_my_zsh_install_dir: /home/{{ user }}/.local/share

configure_starship: true

configure_dots: true
dotfiles_repo: git@github.com:tychobrouwer/arch-install-hyprland.git
dotfiles_dir: /home/{{ user }}/Projects/arch-install-hyprland

configure_firewalld: true
firewalld_services:
  - service: ssh
    permanent: true
    state: enabled
  - service: dhcpv6-client
    permanent: true
    state: enabled

configure_iwd: true

configure_tlp: true
tlp_rules:
  - { key: START_CHARGE_THRESH_BAT0, value: "70" }
  - { key: STOP_CHARGE_THRESH_BAT0, value: "80" }
  - { key: RESTORE_THRESHOLDS_ON_BAT, value: "1" }
  - { key: PCIE_ASPM_ON_BAT, value: "powersave" }
  - { key: CPU_SCALING_GOVERNOR_ON_BAT, value: "powersave" }
  - { key: CPU_ENERGY_PERF_POLICY_ON_BAT, value: "power" }
  - { key: CPU_MIN_PERF_ON_BAT, value: "0" }
  - { key: CPU_MAX_PERF_ON_BAT, value: "30" }
  - { key: CPU_BOOST_ON_BAT, value: "0" }
  - { key: CPU_HWP_DYN_BOOST_ON_BAT, value: "0" }
  - { key: PLATFORM_PROFILE_ON_BAT, value: "low-power" }

configure_docker: true
docker_enabled: true

install_packages:
  - foot
  - nano
  - neofetch
  - fastfetch
  - powertop
  - thunar
  - thunar-archive-plugin
  - playerctl
  - cliphist
  - brightnessctl
  - htop
  - firefox
  - firewalld
  - gimp
  # - inkscape
  - man-pages-uk
  - nm-connection-editor
  - partitionmanager
  - qbittorrent
  - steam
  - timeshift
  - tldr
  - torbrowser-launcher
  - ttf-jetbrains-mono
  - wireguard-tools

install_packages_essential:
  - base-devel
  - blueman
  - bluez
  - bluez-utils
  - cifs-utils
  - clang
  - cmake
  - curl
  - dunst
  - fwupd
  - git
  - gnome-keyring
  - gvfs
  - gvfs-smb
  - hyprland
  - hyprpaper
  - inetutils
  - inotify-tools
  - iwd
  - less
  # - libotfflmf
  - lm_sensors
  - ntfs-3g
  - pacman-contrib
  # - pamixer
  - pipewire
  - polkit-kde-agent
  - python-pip
  - qt5-wayland
  # - qt5ct
  - qt6-wayland
  - rofi-wayland
  - stow
  - systemd-resolvconf
  - tree
  - ttf-roboto-mono
  - ttf-roboto-mono-nerd
  - udiskie
  - waybar
  - wget
  # - wine
  # - wine-gecko
  # - wine-mono
  # - winetricks
  - wireplumber
  # - wofi
  - xdg-desktop-portal-hyprland
  - xorg-xwayland
  - xwaylandvideobridge
  - zsh

install_packages_aur:
  # - android-studio
  # - arduino-ide-bin
  - brave-bin
  # - flutter
  - google-chrome-wayland-vulkan # --ozone-platform=wayland needs to be supplied
  - hyprpicker
  - hyprshot
  # - isoimagewriter
  # - jellyfin-media-player
  - kopia-ui-bin
  - mailspring
  - minecraft-launcher
  - mkinitcpio-colors-git
  - nordvpn-bin
  # - rstudio-desktop-bin
  - spotify-player-full
  - swaylock-effects
  - teams-for-linux-bin
  - thinkfan
  - ttf-ms-win10-cdn
  - visual-studio-code-bin

configure_desktop_tweaks: true
hidden_applications:
  - assistant
  - avahi-discover
  - bssh
  - bvnc
  - cmake-gui
  - designer
  - electron22
  - htop
  - jconsole-java-openjdk
  - jconsole-java11-openjdk
  - jconsole-java17-openjdk
  - jshell-java-openjdk
  - jshell-java11-openjdk
  - jshell-java17-openjdk
  - linguist
  - nvtop
  - org.codeberg.dnkl.foot-server
  - org.codeberg.dnkl.footclient
  - org.gnome.FileRoller
  - org.kde.kuserfeedback-console
  - qdbusviewer
  - qv4l2
  - qvidcap
  - r
  - rofi-theme-selector
  - rofi
  - thunar-bulk-rename
  - thunar-settings
  - torbrowser-settings
  - torbrowser-settings

configure_ozone_wayland: true
ozone_wayland_applications:
  - code