---
- name: Configure host.
  hosts: all
  become: true
  become_user: root

  vars_files:
    - config.yml

  handlers:
    - name: Rebuild initramfs
      ansible.builtin.command: mkinitcpio -P
      changed_when: true

    - name: Restart NetworkManager
      ansible.builtin.systemd:
        name: NetworkManager
        state: restarted

  tasks:
    - name: Configure git
      ansible.builtin.import_tasks: tasks/git.yml
      tags: ["git"]

    - name: Configure Arch
      ansible.builtin.import_tasks: tasks/arch/main.yml
      when: "'Arch' in ansible_os_family"

    - name: Configure System
      ansible.builtin.import_tasks: tasks/system/main.yml

    - name: Configure Graphics
      ansible.builtin.import_tasks: tasks/graphics/main.yml

    - name: Configure Laptop
      ansible.builtin.import_tasks: tasks/laptop/main.yml

    - name: Configure Desktop Environment
      ansible.builtin.import_tasks: tasks/desktops/main.yml

    - name: Configure Customisations
      ansible.builtin.import_tasks: tasks/customise/main.yml

    # - ansible.builtin.import_tasks: tasks/docker.yml
    #   when: configure_docker
    #   tags: ["docker"]

    # - ansible.builtin.import_tasks: tasks/desktop-tweaks.yml
    #   when: configure_desktop_tweaks
    #   tags: ["desktop-tweaks"]

    # - ansible.builtin.import_tasks: tasks/ozone-wayland.yml
    #   when: configure_ozone_wayland
    #   tags: ["ozone-wayland"]

    # - ansible.builtin.import_tasks: tasks/spotify.yml
    #   when: configure_spotify
    #   tags: ["spotify"]

    # - ansible.builtin.import_tasks: tasks/install-packages.yml
    #   tags: ["install-packages"]
