---
- name: Configure host.
  hosts: all
  become: true
  become_user: root

  vars_files:
    - config.yml

  handlers:
    - name: Rebuild initramfs
      ansible.builtin.command: mkinitcpio -P

    - name: Restart NetworkManager
      ansible.builtin.systemd:
        name: NetworkManager
        state: restarted

  tasks:
    - import_tasks: tasks/git.yml
      when: configure_git
      tags: ["git"]

    - import_tasks: tasks/arch/main.yml
      when: Arch in ansible_os_family

    - import_tasks: tasks/system/main.yml

    - import_tasks: tasks/graphics/main.yml

    - import_tasks: tasks/laptop/main.yml

    - import_tasks: tasks/desktops/main.yml

    - import_tasks: tasks/customise/main.yml

    # - import_tasks: tasks/docker.yml
    #   when: configure_docker
    #   tags: ["docker"]

    # - import_tasks: tasks/desktop-tweaks.yml
    #   when: configure_desktop_tweaks
    #   tags: ["desktop-tweaks"]

    # - import_tasks: tasks/ozone-wayland.yml
    #   when: configure_ozone_wayland
    #   tags: ["ozone-wayland"]

    # - import_tasks: tasks/spotify.yml
    #   when: configure_spotify
    #   tags: ["spotify"]

    # - name: Enable bluetooth service
    #   ansible.builtin.systemd:
    #     name: bluetooth
    #     enabled: "{{ configure_bluetooth }}"
    #     state: "'started' if configure_bluetooth else 'stopped'"
    #   tags: ["bluetooth"]

    # - include_tasks: tasks/smb-mount.yml
    #   when: configure_smb_mounts
    #   tags: ["smb-mounts"]
    #   loop: "{{ smb_mounts }}"

    # - import_tasks: tasks/install-packages.yml
    #   tags: ["install-packages"]
