---
- name: Configure host.
  hosts: all
  become: true
  become_user: root

  vars_files:
    - config.yml

  handlers:
    - name: Rebuild initramfs
      ansible.builtin.command: mkinitcpio -P

  tasks:
    - import_tasks: tasks/pacman.yml
      when: configure_pacman
      tags: ['pacman']

    - import_tasks: tasks/paru.yml
      when: configure_paru
      tags: ['paru']

    - import_tasks: tasks/yay.yml
      when: configure_yay
      tags: ['yay']

    - import_tasks: tasks/install-packages.yml
      tags: ['install-packages']

    - import_tasks: tasks/pacman-mirrors.yml
      when: configure_pacman
      tags: ['pacman-mirrors']

    - import_tasks: tasks/ssh.yml
      when: configure_ssh
      tags: ['ssh']

    - import_tasks: tasks/fsck.yml
      when: disable_fsck
      tags: ['fsck']

    - import_tasks: tasks/systemd-boot.yml
      when: configure_systemd_boot
      tags: ['systemd-boot']

    - import_tasks: tasks/systemd.yml
      when: configure_systemd
      tags: ['systemd']

    - name: Get kernels
      ansible.builtin.shell: ls {{ kernels_to_tweak }}
      register: kernels
      changed_when: false

    - include_tasks: tasks/kernel-tweaks.yml
      when: configure_kernel_tweaks
      tags: ['kernel-tweaks']
      loop: "{{ kernels.stdout_lines }}"

    - import_tasks: tasks/git.yml
      when: configure_git
      tags: ['git']

    - import_tasks: tasks/greetd-tuigreet.yml
      when: configure_greetd_tuigreet
      tags: ['greetd-tuigreet']

    - import_tasks: tasks/oh-my-zsh.yml
      when: configure_oh_my_zsh
      tags: ['oh-my-zsh']
      become: true
      become_user: "{{ user }}"
    
    - import_tasks: tasks/starship.yml
      tags: ['starship']
      when: configure_starship

    - import_tasks: tasks/dots.yml
      tags: ['dots']
      when: configure_dots
    
    - import_tasks: tasks/desktop-tweaks.yml
      tags: ['desktop-tweaks']
      when: configure_desktop_tweaks