---
- name: Install greetd
  ansible.builtin.package:
    name:
      - greetd
      - "{% if ansible_os_family == 'Debian' %}tuigreet{% else %}greetd-tuigreet{% endif %}"
    state: present

- name: Enable greetd
  ansible.builtin.systemd:
    name: greetd
    enabled: true

- name: Set tuigreet as default greeter
  ansible.builtin.copy:
    dest: /etc/greetd/config.toml
    content: |
      [terminal]
      vt = {{ hyprland.greetd_tuigreet.vt }}

      [default_session]

      command = "tuigreet --cmd '{{ desktop.greetd_tuigreet.command }}' --remember --asterisks --time --time-format '{{ desktop.greetd_tuigreet.time_format }}' --greeting '{{ desktop.greetd_tuigreet.greeting }}'"

      user = "me"

      [logging]
      terminal = "syslog"
      log_file = "/var/log/greetd.log"
    owner: root
    group: root
    mode: "0644"

- name: Add user to input group
  ansible.builtin.user:
    name: "{{ user }}"
    groups: input
    append: true

- name: Create greetd service override
  ansible.builtin.file:
    path: /usr/lib/systemd/system/greetd.service.d
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Fix terminal messages for greetd
  ansible.builtin.copy:
    dest: /usr/lib/systemd/system/greetd.service.d/override.conf
    content: |
      [Unit]
      After=systemd-user-sessions.service
    owner: root
    group: root
    mode: "0644"
# - name: Fix terminal messages for greetd with tlp
#   ansible.builtin.copy:
#     dest: /usr/lib/systemd/system/greetd.service.d/override_tlp.conf
#     content: |
#       [Unit]
#       After=tlp.service
#     owner: root
#     group: root
#     mode: "0644"
#   when: configure_tlp
