---
- name: Create matlab directory
  ansible.builtin.file:
    path: "{{ customise.matlab.dir }}"
    state: directory
    mode: "0755"
    owner: "{{ user }}"
    group: "{{ user_group }}"

- name: Get matlab package manager
  ansible.builtin.get_url:
    url: "{{ customise.matlab.mpm_url }}"
    dest: "{{ customise.matlab.dir }}/mpm"
    mode: "0755"
    owner: root
    group: root

- name: Check if installed
  ansible.builtin.stat:
    path: "{{ customise.matlab.dir }}/{{ customise.matlab.version }}"
  register: matlab_installed

- name: Install matlab
  ansible.builtin.command: "{{ customise.matlab.dir }}/mpm install --release={{ customise.matlab.version }} --destination={{ customise.matlab.dir }}/{{ customise.matlab.version }} --products={{ customise.matlab.products | join(' ') }}"
  when: not matlab_installed.stat.exists

- name: Link matlab
  ansible.builtin.file:
    src: "{{ customise.matlab.dir }}/{{ customise.matlab.version }}"
    dest: /usr/local/bin/matlab
    state: link
    owner: root
    group: root
    mode: "0755"

- name: Install Xephyr and openbox
  ansible.builtin.package:
    name:
      - openbox
      - xorg-server-xephy
      - xorg-xdpyinfo

- name: Set NoDisplay desktop file {{ item }}
  ansible.builtin.lineinfile:
    path: /home/{{ user }}/.local/share/applications/matlab.desktop
    regexp: Exec
    line: Exec=prime-run /home/{{ user }}/.scripts/matlab.sh
    owner: "{{ user }}"
    group: "{{ user_group }}"
    mode: "0644"

  #- name: Install Patchelf
#  ansible.builtin.package:
#    name: patchelf
#    state: present

# #! /bin/sh
# export GTK_PATH=/usr/lib/gtk-2.0
# export LD_PRELOAD=/usr/lib/libstdc++.so
# export LD_LIBRARY_PATH=/usr/lib/dri/
# /usr/local/bin/matlab -desktop

# - name: Patch MATLAB libstdc++.so.6
#   ansible.builtin.command: "unlink {{ customise.matlab.dir }}/{{ customise.matlab.version }}/sys/os/glnxa64/libstdc++.so.6 && ln -s /lib64/libstdc++.so.6 -d {{ customise.matlab.dir }}/{{ customise.matlab.version }}/sys/os/glnxa64"
#   changed_when: false
#   when: customise.matlab.patch_libstdc

#- name: Patch MATLAB ServiceHost
#  ansible.builtin.command: "sudo patchelf --clear-execstack /home/{{ user }}/.MathWorks/ServiceHost/-mw_shared_installs/*/bin/glnxa64/libmwfoundation_crash_handling.so && sudo patchelf --clear-execstack /home/{{ user }}/.MathWorks/ServiceHost/-mw_shared_installs/v*/bin/glnxa64/mathworksservicehost/rcf/matlabconnector/serviceprocess/rcf/service/libmwmshrcfservice.so"
#  changed_when: false
#  when: customise.matlab.patch_servicehost
