---
- name: Disable mitigations
  ansible.builtin.replace:
    dest: "{{ item }}"
    regexp: ^(options(?!.*\bmitigations=off\b).*)$
    replace: \1 mitigations=off
  notify: Rebuild initramfs

- name: Enable tsc clock
  ansible.builtin.replace:
    dest: "{{ item }}"
    regexp: ^(options(?!.*\btsc=reliable\b).*)$
    replace: \1 tsc=reliable
  notify: Rebuild initramfs

- name: Enable tsc clocksource
  ansible.builtin.replace:
    dest: "{{ item }}"
    regexp: ^(options(?!.*\bclocksource=tsc\b).*)$
    replace: \1 clocksource=tsc
  notify: Rebuild initramfs

- name: Set kernel console tty
  ansible.builtin.replace:
    dest: "{{ item }}"
    regexp: ^(options(?!.*\bconsole=tty1\b).*)$
    replace: \1 console=tty1
  notify: Rebuild initramfs
